batch_size: 64
data:
  class_indice_file: data/metadata/class_label_indices.txt
  feature: data/dev/feature.csv
  label: data/dev/label.csv
  stratified: true
dataloader_args:
  batch_size: 64
  num_workers: 1
early_stop: 7
epochs: 100
eval_data:
  feature: data/eval/feature.csv
  label: data/eval/label.csv
loss: BceLoss
model:
  args:
    gru_layers: 2
  type: Crnn
num_workers: 2
optimizer:
  args:
    lr: 0.001
  type: AdamW
outputpath: experiments_data_aug/
scheduler_args:
  factor: 0.1
  patience: 3
